#!/bin/bash
export KERNELDIR=`readlink -f .`
export RAMFS_SOURCE=`readlink -f $KERNELDIR/recovery`
export USE_SEC_FIPS_MODE=true

echo "kerneldir = $KERNELDIR"
echo "ramfs_source = $RAMFS_SOURCE"

RAMFS_TMP="/tmp/arter97-recovery"

echo "ramfs_tmp = $RAMFS_TMP"
cd $KERNELDIR

if [ "${1}" = "skip" ] ; then
	echo "Skipping Compilation"
else
	echo "Compiling kernel"
	cp defconfig .config
        scripts/configcleaner "
CONFIG_SWAP
CONFIG_IOSCHED_DEADLINE
CONFIG_IOSCHED_FIFO
CONFIG_IOSCHED_CFQ
CONFIG_IOSCHED_VR
CONFIG_IOSCHED_SIO
CONFIG_IOSCHED_ZEN
CONFIG_DEFAULT_DEADLINE
CONFIG_DEFAULT_CFQ
CONFIG_DEFAULT_SIO
CONFIG_DEFAULT_VR
CONFIG_DEFAULT_ZEN
CONFIG_KSM
CONFIG_UKSM
CONFIG_KSM_LEGACY
CONFIG_CLEANCACHE
CONFIG_FRONTSWAP
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
CONFIG_CPU_FREQ_DEFAULT_GOV_PEGASUSQ
CONFIG_CPU_FREQ_GOV_POWERSAVE
CONFIG_CPU_FREQ_GOV_USERSPACE
CONFIG_CPU_FREQ_GOV_HOTPLUG
CONFIG_CPU_FREQ_GOV_ONDEMAND
CONFIG_CPU_FREQ_GOV_ONDEMAND_FLEXRATE
CONFIG_CPU_FREQ_GOV_INTERACTIVE
CONFIG_CPU_FREQ_GOV_CONSERVATIVE
CONFIG_CPU_FREQ_GOV_SMARTASS2
CONFIG_CPU_FREQ_GOV_ZZMOOVE
CONFIG_CPU_FREQ_GOV_ADAPTIVE
CONFIG_CPU_FREQ_GOV_PEGASUSQ
CONFIG_CPU_FREQ_GOV_YANKASUSQ
CONFIG_CPU_FREQ_GOV_PEGASUSQPLUS
CONFIG_CPU_FREQ_GOV_LULZACTIVEQ
CONFIG_HIBERNATION
CONFIG_TCP_CONG_ADVANCED
CONFIG_TCP_CONG_BIC
CONFIG_TCP_CONG_WESTWOOD
CONFIG_TCP_CONG_HTCP
CONFIG_TCP_CONG_HSTCP
CONFIG_TCP_CONG_HYBLA
CONFIG_TCP_CONG_VEGAS
CONFIG_TCP_CONG_SCALABLE
CONFIG_TCP_CONG_LP
CONFIG_TCP_CONG_VENO
CONFIG_TCP_CONG_YEAH
CONFIG_TCP_CONG_ILLINOIS
CONFIG_DEFAULT_BIC
CONFIG_DEFAULT_CUBIC
CONFIG_DEFAULT_HTCP
CONFIG_DEFAULT_HYBLA
CONFIG_DEFAULT_VEGAS
CONFIG_DEFAULT_VENO
CONFIG_DEFAULT_WESTWOOD
CONFIG_DEFAULT_RENO
CONFIG_DEFAULT_TCP_CONG
CONFIG_TOUCH_WAKE
CONFIG_BCM4334
CONFIG_BROADCOM_WIFI_RESERVED_MEM
CONFIG_WLAN_REGION_CODE
CONFIG_BATTERY_MAX77693_CHARGER_CONTROL
CONFIG_FB_S5P_MDNIE_CONTROL
CONFIG_SND_BOEFFLA
CONFIG_HIDRAW
CONFIG_ZRAM
CONFIG_ZRAM_DEBUG
CONFIG_ZRAM_FOR_ANDROID
CONFIG_ZCACHE
CONFIG_ZSMALLOC
CONFIG_EXT2_FS
CONFIG_EXT2_FS_XATTR
CONFIG_EXT2_FS_XIP
CONFIG_NTFS_FS
CONFIG_NTFS_DEBUG
CONFIG_NTFS_RW
CONFIG_F2FS_STAT_FS
CONFIG_NETWORK_FILESYSTEMS
CONFIG_NFS_FS
CONFIG_NFS_V3
CONFIG_NFS_V3_ACL
CONFIG_NFS_V4
CONFIG_NFSD
CONFIG_LOCKD
CONFIG_LOCKD_V4
CONFIG_NFS_ACL_SUPPORT
CONFIG_NFS_COMMON
CONFIG_SUNRPC
CONFIG_CEPH_FS
CONFIG_CIFS
CONFIG_CIFS_STATS
CONFIG_CIFS_STATS2
CONFIG_CIFS_WEAK_PW_HASH
CONFIG_CIFS_UPCALL
CONFIG_CIFS_XATTR
CONFIG_CIFS_POSIX
CONFIG_CIFS_DEBUG2
CONFIG_CIFS_DFS_UPCALL
CONFIG_CIFS_ACL
CONFIG_NCP_FS
CONFIG_CODA_FS
CONFIG_AFS_FS
CONFIG_USB_ANDROID_FOR_RECOVERY
CONFIG_MODULES
CONFIG_RD_LZMA
CONFIG_RD_LZO
CONFIG_DECOMPRESS_LZMA
CONFIG_DECOMPRESS_LZO
CONFIG_KALLSYMS
"
	echo "
# CONFIG_SWAP is not set
# CONFIG_IOSCHED_DEADLINE is not set
# CONFIG_IOSCHED_FIFO is not set
# CONFIG_IOSCHED_CFQ is not set
# CONFIG_IOSCHED_VR is not set
# CONFIG_IOSCHED_SIO is not set
# CONFIG_IOSCHED_ZEN is not set
# CONFIG_KSM is not set
# CONFIG_CLEANCACHE is not set
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y
# CONFIG_CPU_FREQ_DEFAULT_GOV_PEGASUSQ is not set
# CONFIG_CPU_FREQ_GOV_POWERSAVE is not set
# CONFIG_CPU_FREQ_GOV_USERSPACE is not set
# CONFIG_CPU_FREQ_GOV_HOTPLUG is not set
# CONFIG_CPU_FREQ_GOV_ONDEMAND is not set
# CONFIG_CPU_FREQ_GOV_INTERACTIVE is not set
# CONFIG_CPU_FREQ_GOV_CONSERVATIVE is not set
# CONFIG_CPU_FREQ_GOV_SMARTASS2 is not set
# CONFIG_CPU_FREQ_GOV_ZZMOOVE is not set
# CONFIG_CPU_FREQ_GOV_ADAPTIVE is not set
# CONFIG_CPU_FREQ_GOV_PEGASUSQ is not set
# CONFIG_CPU_FREQ_GOV_YANKASUSQ is not set
# CONFIG_CPU_FREQ_GOV_PEGASUSQPLUS is not set
# CONFIG_CPU_FREQ_GOV_LULZACTIVEQ is not set
# CONFIG_TCP_CONG_ADVANCED is not set
CONFIG_DEFAULT_TCP_CONG="cubic"
# CONFIG_TOUCH_WAKE is not set
# CONFIG_BCM4334 is not set
# CONFIG_BATTERY_MAX77693_CHARGER_CONTROL is not set
# CONFIG_FB_S5P_MDNIE_CONTROL is not set
# CONFIG_SND_BOEFFLA is not set
# CONFIG_HIDRAW is not set
# CONFIG_ZRAM is not set
# CONFIG_ZSMALLOC is not set
# CONFIG_EXT2_FS is not set
# CONFIG_NTFS_FS is not set
# CONFIG_F2FS_STAT_FS is not set
# CONFIG_NETWORK_FILESYSTEMS is not set
CONFIG_USB_ANDROID_FOR_RECOVERY=y
# CONFIG_MODULES is not set
# CONFIG_RD_LZMA is not set
CONFIG_RD_LZO=y
# CONFIG_DECOMPRESS_LZMA is not set
CONFIG_DECOMPRESS_LZO=y
# CONFIG_KALLSYMS is not set
" >> .config
	sed -i -e 's/-Ofast/-Os/g' Makefile
	make "$@" || exit 1
	git checkout Makefile
fi

echo "Building new ramdisk"
#remove previous ramfs files
rm -rf '$RAMFS_TMP'*
rm -rf $RAMFS_TMP
rm -rf $RAMFS_TMP.cpio
#copy ramfs files to tmp directory
cp -ax $RAMFS_SOURCE $RAMFS_TMP
cd $RAMFS_TMP

$KERNELDIR/ramdisk_fix_permissions.sh 2>/dev/null

find . -name '*.sh' -exec chmod 755 {} \;
#clear git repositories in ramfs
find . -name .git -exec rm -rf {} \;
find . -name EMPTY_DIRECTORY -exec rm -rf {} \;
cd $KERNELDIR
rm -rf $RAMFS_TMP/tmp/*

cd $RAMFS_TMP
find . | fakeroot cpio -H newc -o | lzop -c -9 > $RAMFS_TMP.cpio.lzo
ls -lh $RAMFS_TMP.cpio.lzo
cd $KERNELDIR

echo "Making new boot image"
gcc -w -s -pipe -O2 -Itools/libmincrypt -o tools/mkbootimg/mkbootimg tools/libmincrypt/*.c tools/mkbootimg/mkbootimg.c
tools/mkbootimg/mkbootimg --kernel $KERNELDIR/arch/arm/boot/zImage --ramdisk $RAMFS_TMP.cpio.lzo --board smdk4x12 --cmdline 'ttySAC2,115200' --base 0x40000000 --pagesize 2048 -o $KERNELDIR/recovery.img
if [ "${1}" = "CC=\$(CROSS_COMPILE)gcc" ] ; then
	dd if=/dev/zero bs=$((8388608-$(stat -c %s recovery.img))) count=1 >> recovery.img
fi

echo "done"
ls -al recovery.img
echo ""
