#!/res/busybox sh

export PATH=/res/asset:$PATH

if [ -f $2 ]; then
	FILEVAR=$(basename $2)

	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			eval $FILEVAR=`cat $2`
			echo $FILEVAR=`cat $2` >> $DEFAULT_PROFILE
		fi
	else
		echo $3 > $2
		eval $FILEVAR=`cat $2`
	fi

	eval echo \$$FILEVAR
fi

if [[ $(cat /sys/devices/platform/samsung-battery/dcp_ac_chrg_curr) -gt $(cat /sys/devices/platform/samsung-battery/dcp_ac_input_curr) ]] ; then
	cat /sys/devices/platform/samsung-battery/dcp_ac_chrg_curr > /sys/devices/platform/samsung-battery/dcp_ac_input_curr
fi
