#!/res/busybox sh

export PATH=/res/asset:$PATH

FILEVAR=$2_iosched

if [ -z $4 ]; then
	evalcmd='eval echo \$$FILEVAR'
	if [ "a`eval $evalcmd`" == "a" ]; then
		VAL=`cat $3 | sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
		if [ -z $VAL ]; then
			VAL=`cat $(echo $3 | sed s/mmcblk1/mmcblk0/g) | sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
		fi
		eval $FILEVAR=$VAL
		echo $FILEVAR=$VAL >> $DEFAULT_PROFILE
	fi
else
	if [ -f $3 ]; then
		echo $4 > $3
		eval $FILEVAR=`cat $3 | sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
	else
		eval $FILEVAR=$4
	fi
fi

eval echo \$$FILEVAR
